### ISSUE TITLE
Using tags to target qubes would simplify the configuration

### ISSUE THREAD

**Issue by gonzalo-bulnes** [gonzalo-bulnes/qubes-mgmt-salt-user#14]
It should be possible: https://gist.github.com/bcduggan/d0ee8a22767b32fc23d063ccf9385623

**Comment by gonzalo-bulnes** [comment]
It turns out that targetting using tags does greatly simplify the formulas, entirely removing the need for setting up specific pillar data. (Assuming all tags are added to the pillar in a generic way like suggested in the gist linked above.)

Tags are ill-fitted to hold list values, though, and in that case QVM Features are another iseful addition to the pillar. (That can be achieved in a very similar way to QVM Tags.)

**Comment by gonzalo-bulnes** [comment]
This is coming. Context: https://forum.qubes-os.org/t/copying-qvm-features-in-salt-pillar-any-reason-not-to-do-that/19277?user=gonzalo-bulnes

**Comment by ben-grande** [comment]
Hello Gonzalo,

Thanks for opensourcing this project.

Do you plan to upstream this to Qubes OS? I think it is very useful (haven't tried it yet) but the tags and features in pillar do make sense to be integrated into Qubes OS Salt environment.

**Comment by gonzalo-bulnes** [comment]
Hi @ben-grande!

I have currently no plans to push for upstream to pick this up. I am not sure it is something I'd personally priotitize integrating if I was working upstream. But the project licensing setup with REUSE should make easy to reuse if you're keen on making that case with the Qubes OS team, and I've chosen licenses to make that possible even if that's not a goal that I plan to pursue myself at the moment.

Does that make sense?

**Comment by ben-grande** [comment]
> I have currently no plans to push for upstream to pick this up. I am not
> sure it is something I'd personally priotitize integrating if I was working
> upstream.
>

I think I can do the PR to merge upstream. Even if they don't prioritize,
they only need to review it, not code anymore.

But the project licensing setup with REUSE should make easy to reuse if
> you're keen on making that case with the Qubes OS team, and I've chosen
> licenses to make that possible even if that's not a goal that I plan to
> pursue myself at the moment.
>
> Does that make sense?
>

Yes,  thanks for using REUSE. If you don't have plans to port upstream, I
will try to solve the R4.2 issue and port upstream, when time allows.

>

**Comment by ben-grande** [comment]
Summitted proposal of inclusion to upstream https://www.mail-archive.com/qubes-devel@googlegroups.com/msg05459.html

**Comment by ben-grande** [comment]
Did not receive a response so far on the mailing list, will try a PR:

- https://github.com/QubesOS/qubes-mgmt-salt-base/pull/17

**Comment by gonzalo-bulnes** [comment]
I _believe_ it can take time to receive feedack from the Qubes OS team when a proposal at an early stage isn't part of, or isn't obviously aligned with the current work in focus. Thanks for following up with the PR @ben-grande !

**Comment by gonzalo-bulnes** [comment]
Well done @ben-grande !  Thanks for seeing the PR through! 👏

**Comment by gonzalo-bulnes** [comment]
I'll close this issue, taking note that the following packages are not needed anymore for R4.2:

- `qubes-mgmt-salt-user-qvm-features-in-pillar`
- `qubes-mgmt-salt-user-qvm-tags-in-pillar`
