### ISSUE TITLE
Testing of qvm-tags-in-pillar under R4.2 is needed!

### ISSUE THREAD

**Issue by gonzalo-bulnes** [gonzalo-bulnes/qubes-mgmt-salt-user#27]
_Opening this issue as a placeholder for @ben-grande's sake. I'll add details (including the full error message) when I've time to investigate further, but help is welcome!_

The default Salt configuration in R4.2  doesn't seem to allow `qvm-tags-in-pillar` and `qvm-features-in-pillar` to work.

I'm not sure what changed since R4.1, but the pillar extensions are consistently reported as "not found" in my early testing.

If anyone was able to confirm this, that would be a great first step towards documenting and troubleshooting the issue so that it can be fixed either upstream if the change of behaviour wasn't intentional, or here if adjustments to those two states are needed.

**Comment by gonzalo-bulnes** [comment]
@ben-grande Heads up, if this issue is confirmed, it affects the feature discussed in #14 and https://github.com/ben-grande/qusal/issues/41 (under R4.2 that is the current Qubes OS version now).

**Comment by gonzalo-bulnes** [comment]
Also heads up @bcduggan in case you've noticed (or not!) this issue yourself. 🙂

**Comment by ben-grande** [comment]
Thanks for the ping.

I can test but in some weeks from now only.

**Comment by gonzalo-bulnes** [comment]
@ben-grande Let me know if you need a hand getting set up when the time comes (e.g. if you decide to go the RPM package way, though the two states are small enough that even a re-write in dom0 shouldn't take too long!)

**Comment by gonzalo-bulnes** [comment]
Might be relevant (or not!)—if I remember correctly the error message was similar but not the same:

> I had the error `[CRITICAL] Specified ext_pillar interface qvm_prefs is unavailable` on a working 4.2 [...]
>
>The recommend command `qubesctl saltutil.sync_all` solved it.
>
> ([source](https://github.com/QubesOS/qubes-issues/issues/8491#issuecomment-2051163050))

**Comment by ben-grande** [comment]
Tested on R4.2 and it works!

> The recommend command qubesctl saltutil.sync_all solved it.

Yes, necessary.

**Comment by ben-grande** [comment]
Was implemented [upstream](https://github.com/QubesOS/qubes-mgmt-salt-base/pull/17), this issue can be closed.

Upstream [syncs modules on installation](https://github.com/QubesOS/qubes-mgmt-salt-base/blob/08b191e1d26e2dfe5eee02e077a890947182dddc/rpm_spec/qubes-mgmt-salt-base.spec.in#L34-L35):
```sh
qubesctl saltutil.clear_cache -l quiet --out quiet > /dev/null || true
qubesctl saltutil.sync_all refresh=true -l quiet --out quiet > /dev/null || true
```
